# Generated by Django 5.2.17 on 2026-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
