# Generated by Django 5.2.17 on 2026-08-18 03:23

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_content_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
